FROM node:alpine As development

WORKDIR /home/node/app

COPY --chown=app:node package*.json ./

# COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app


COPY package*.json ./

RUN npm install --only=production

COPY . .

COPY --from=development /usr/src/app/dist ./dist

USER node

CMD ["node", "dist/apps/products/main"]